services:
  market-data-service:
    build: .
    container_name: market-data-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - DB_HOST=${DB_HOST_DOCKER}
      - DB_PORT=${DB_PORT_DOCKER}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - exchange-net
    depends_on:
      - market-data-db

  market-data-db:
    image: postgres:15
    container_name: market-data-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - exchange-net
    volumes:
      - market-data-db-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  market-data-db-data:

networks:
  exchange-net:
    external: true